### PR TITLE
Bug 1959546: Update to current master

### PR DESCRIPTION
**Pull request by jsafrane**
As part of bug [#1959546](https://bugzilla.redhat.com/show_bug.cgi?id=1959546) and  [1934180](https://bugzilla.redhat.com/show_bug.cgi?id=1934180), it makes sense to merge current master branch.

Benefits:

* Unit test coverage (most of the Files changed are XMLs for simulated vCenter that we use for unit tests).
* Bugfixes (perhaps more than the two above).
* As you can see below, the nr. of commits that we merge here is not that big.

Risks:

* Newer  govc version 0.23 (another big chunk of Files changed)

WIP:
~* needs discussion with QA~

### CODE REVIEW

**Comment by gnufied** [comment]
I tested this on a 4.7 cluster where I was using datastore cluster and it seems be working:

521 02:14:49.160183       1 datastore.go:56] CheckStorageClasses: dsc: datastore team-ssd-intel is part of intel-ds-cluster datastore cluster
I0521 02:14:49.160200       1 datastore.go:67] CheckStorageClasses checked 2 storage classes, 1 problems found
I0521 02:14:49.160207       1 operator.go:241] CheckStorageClasses failed: StorageClass dsc: datastore team-ssd-intel is part of intel-ds-cluster datastore cluster

**Comment by sdodson** [comment]
[patch-manager] I evaluated this last week and skipped it due to the size and the fact that the bugs referenced only moved to MODIFIED on May 17th. Finally, we were constrained on capacity last week as well. We will re-evaluate when the merge window opens again later this week.

**Comment by wking** [comment]
We probably want openshift/cluster-storage-operator#169 to go in first anyway, so we remain covered in one way or another, and that PR is still waiting on lgtm/approval.

**Comment by gnufied** [comment]
@wking  if we merge https://github.com/openshift/cluster-storage-operator/pull/169 first then - it will try to alert of metric that does not exist. It may not matter in the end because both PRs needs to be picked.

**Pull request merged**
