### PR TITLE
OCPBUGS-24401: Use failure-domains and other changes from master

### PR DESCRIPTION
**Pull request by gnufied**
Fixes https://issues.redhat.com/browse/OCPBUGS-24401

I used following code:

`git merge master` 

This brings other changes to 4.14 branch too, but Dockerfile and dependencies are kept from release-4.14 branches.

### CODE REVIEW

**Comment by jsafrane** [comment]
/label backport-risk-assessed
anyone can lgmt, however, I don't like -zones job failing. So far it failed during various stages of cluster installation.

**Comment by gnufied** [comment]
@duanwei33 lets also check for https://issues.redhat.com/browse/OCPBUGS-926 and ensure we haven't introduced regression here.

**Comment by gnufied** [comment]
Putting on hold while we wait for confirmation from @duanwei33 

/hold

**Comment by duanwei33** [comment]
@gnufied Hi, with the open PR, I verified https://issues.redhat.com/browse/OCPBUGS-24401, but need some more time for https://issues.redhat.com/browse/OCPBUGS-926.

**Comment by duanwei33** [comment]
I did some tests with minimum permissions, only ESXi host version check failed if the computecluster is Read-only, but this is not introduced by this PR, will track it individually.

/label qe-approved

**Pull request merged**
